#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.4.33f1_d75f7e9df24c"
#define UNITY_VERSION_FULL_NICE "2018.4.33f1 (d75f7e9df24c)"
#define UNITY_VERSION_BLD 14114686
#define UNITY_VERSION_DATE 1616109821
#define UNITY_VERSION_WIN "2018.4.33.14114686"
#define UNITY_VERSION_BRANCH "2018.4/staging"
